# Default values for minecraft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ********REQUIRED********
node:
  hostname: 'mk8s01' # Your kube node's hostname
# ************************

minecraft:
  gamemode: 'creative'
  motd: 'Just another Minecraft Server' # Message of the Day
  port: 25565

volume:
  storage: 10Gi
  path: '/home/ubuntu/minecraft-data' # Path to wherever you want to save your worldfile

resources:
  limits:
    memory: 8Gi
  requests:
    memory: 6Gi

serviceAccount:
  create: true
